name: Publish Wispe React

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Override npm dist-tag (defaults to "latest")'
        required: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Node.js & authenticate to npm
      - name: Set up Node.js & authenticate
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build wispe-react
      - name: Build wispe-react
        run: npx nx build wispe-react

      # 5) Publish to npm
      - name: Publish to npm
        working-directory: packages/wispe-react/dist
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "Publishing to npm with tag '${{ github.event.inputs.tag }}'"
            npm publish --tag "${{ github.event.inputs.tag }}"
          else
            echo "Publishing to npm with default tag (latest)"
            npm publish
          fi
